apiVersion: v1
kind: Service
metadata:
  namespace: url_shorter
  labels:
    run: url_shorter
  name: url_shorter
spec:
  ports:
  - port: 5488
    targetPort: 5488
    protocol: TCP
  selector:
      run: url_shorter